// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDOWpY-F34inHBnshAHKVyuTfq2Inne00',
    appId: '1:838703491118:web:e6d0b506336b02a43817bf',
    messagingSenderId: '838703491118',
    projectId: 'hubble-intentgenesiscorp',
    authDomain: 'hubble-intentgenesiscorp.firebaseapp.com',
    databaseURL: 'https://hubble-intentgenesiscorp-default-rtdb.firebaseio.com',
    storageBucket: 'hubble-intentgenesiscorp.firebasestorage.app',
    measurementId: 'G-75Z9G40T8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5UZUX84N7KoYlkaIckyJGAPjiQfVwxQQ',
    appId: '1:838703491118:android:30c11eb2c754d7e83817bf',
    messagingSenderId: '838703491118',
    projectId: 'hubble-intentgenesiscorp',
    databaseURL: 'https://hubble-intentgenesiscorp-default-rtdb.firebaseio.com',
    storageBucket: 'hubble-intentgenesiscorp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzosP_2RNpZbGY_jKt2F2DcreSnI0holU',
    appId: '1:838703491118:ios:b403ccb5a1aee79f3817bf',
    messagingSenderId: '838703491118',
    projectId: 'hubble-intentgenesiscorp',
    databaseURL: 'https://hubble-intentgenesiscorp-default-rtdb.firebaseio.com',
    storageBucket: 'hubble-intentgenesiscorp.firebasestorage.app',
    iosClientId: '838703491118-dmgd91917g06kc8m4q8jcrcdici9ehev.apps.googleusercontent.com',
    iosBundleId: 'com.example.hubble',
  );
}
